cms/urls.py
from django.conf.urls import patterns, include, url

from cms.feeds import LastArticles

urlpatterns = patterns('',
    (r'^rss/$', LastArticles()),
)
urlpatterns += patterns('cms.views',
    url(r'^category/(?P<category_slug>.*?)/$', 'pages', name='category'),
    url(r'^$', 'pages', name='pages'),
    url(r'^(?P<slug>.*?)/$', 'page', name='page'),
)

movase/urls.py
from django.conf.urls import patterns, include, url

from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    (r'^ckeditor/', include('ckeditor.urls')),

    (r'^pages/', include('cms.urls')),
    (r'^tags/', include('tags.urls')),
    # (r'^contact/', include('contact.urls')),

    url(r'^$', 'movase.views.index', name='home'),
)

if settings.LOCAL:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tags/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('tags.views',
    url(r'^$', 'tags', name='tags'),
    url(r'^(?P<tag_name>.*?)/$', 'tag', name='tag'),
)

tags/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.generic import GenericForeignKey
from django.core.urlresolvers import reverse
from django.db.models import Count

class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)
    
    class Meta:
        ordering = ('name',)
    
    def __unicode__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('tag', kwargs={'tag_name': self.name})


class TagManager(models.Manager):
    def top_tags(self, max=15):
        top = self.model.objects.values('tag__name').annotate(score=Count('tag')).order_by('-score')[:max]
        
        return top


class TagItem(models.Model):
    class Meta:
        unique_together = ('tag', 'content_type', 'object_id')

    tag = models.ForeignKey('Tag')
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField(db_index=True)
    obj = GenericForeignKey('content_type', 'object_id')
    
    objects = TagManager()

tags/forms.py
# -*- coding: utf-8 -*-
from django import forms
from tags import get_tags

class FormTags(forms.ModelForm):
    
    tags = forms.CharField(max_length=400, required=False, help_text=u"Digite as palavras-chave separadas por vírgula")
    
    def __init__(self, *args, **kwargs):
        super(FormTags, self).__init__(*args, **kwargs)

        if self.instance.id:
            self.initial['tags'] = get_tags(self.instance)

tags/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext

from models import Tag

def tags(request):
    list = Tag.objects.all()
    return render_to_response(
        'tags/tags.html',
        locals(),
        context_instance=RequestContext(request),
    )

def tag(request, tag_name):
    tag = get_object_or_404(Tag, name=tag_name)
    return render_to_response(
        'tags/tag.html',
        locals(),
        context_instance=RequestContext(request),
    )

tags/templates/tags/show_tags.html
{% load tags_tags %}

{% for tag in object|get_tags %}
<a class="category" href="{{ tag.get_absolute_url }}">{{ tag }}</a>{% if not forloop.last %},{% endif %}
{% endfor %}

tags/templates/tags/tag.html
{% extends 'layout.html' %}

{% block title %} Tag "{{ tag.name }}" {% endblock %}

{% block content %}
<div>
    <article role="article">
        <h1>Tag "{{ tag.name }}"</h1>
        <ul>
            {% for item in tag.tagitem_set.all %}
            {% if item.obj %}
            <li><a href="{{ item.obj.get_absolute_url }}">{{ item.obj }}</a></li>
            {% endif %}
            {% endfor %}
        </ul>
    </article>
</div>
{% endblock %}

tags/templates/tags/tags.html
{% extends 'layout.html' %}

{% block title %} Tags {% endblock %}

{% block content %}
<div>
    <article role="article">
        <h1>Tags</h1>
        <p>
            {% for tag in list %}
            {% if tag|slugify %}
            <div style="float: left;">
                <a href="{{ tag.get_absolute_url }}">{{ tag }}</a> &nbsp;|&nbsp;
            </div>
            {% endif %}
            {% endfor %}
        </p>
    </article>
</div>
{% endblock %}